{
 "title": "API GATEWAY",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Goroutine",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "goroutine" } },
   "targets": [
    {
     "expr": "rate(go_goroutines{instance=\"btw-api-v2-service:3002\"}[1m]) * 100",
     "legendFormat": "Goroutine {{instace}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"btw-api-v2-service:3002\"}",
     "legendFormat": "Memory Usage {{instance}}"
    },
    {
     "expr": "go_memstats_alloc_bytes{instance=\"btw-api-v2-service:3002\"}",
     "legendFormat": "Memory Heap Usage {{instance}}"
    },
    {
     "expr": "go_memstats_sys_bytes{instance=\"btw-api-v2-service:3002\"}",
     "legendFormat": "Go Allocated Memory {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mCPU" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"btw-api-v2-service:3002\"}[1m]) * 1000",
     "legendFormat": "CPU Usage Total {{instance}}"
    }
   ]
  },
  {
   "title": "Requests Latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path) (rate(api_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Path {{path}}"
    }
   ]
  },
  {
   "title": "Total Request by Path",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(api_request_total[$__rate_interval]) * 10",
     "legendFormat": "Path {{path}}"
    }
   ]
  },
  {
   "title": "Total Request by HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(code) (rate(api_request_total[$__rate_interval])) * 10",
     "legendFormat": "Status {{code}}"
    }
   ]
  }
 ]
}