global:
  # DO NOT use this value in production, it's only for demo purposes
  # I usually use around 15s or 30s value
  scrape_interval: 10s
scrape_configs:
  - job_name: 'api-server'
    static_configs:
      - targets:
          - api:3001